all:
  children:
    k3s_cluster:
      children:
        k3s_masters:
          hosts:
            k3s-control:
              ansible_host: 10.0.0.130
        k3s_workers:
          hosts:
            k3s-agent:
              ansible_host: 10.0.0.99
      vars:
        ansible_user: pooch
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_python_interpreter: /usr/bin/python3
        
