- name: Setup K3s Control Plane
  hosts: k3s_masters
  become: yes
  vars:
    k3s_server_args: >-
      --write-kubeconfig-mode=644
      --cluster-cidr=10.42.0.0/16
      --service-cidr=10.43.0.0/16
      
  tasks:
    - name: Check if K3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_installed
      
    - name: Install K3s server
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server {{ k3s_server_args }}
      when: not k3s_installed.stat.exists
      
    - name: Wait for K3s to be ready
      wait_for:
        port: 6443
        host: "{{ ansible_host }}"
        timeout: 300
        
    - name: Get node token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
      
    - name: Display kubeconfig copy instructions
      debug:
        msg: |
          K3s cluster is ready!
          To copy kubeconfig manually, run:
          scp ubuntu@{{ ansible_host }}:/etc/rancher/k3s/k3s.yaml ~/.kube/config
          sed -i 's/127.0.0.1/{{ ansible_host }}/g' ~/.kube/config

- name: Setup K3s Worker Nodes
  hosts: k3s_workers
  become: yes
  tasks:
    - name: Check if K3s agent is installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_agent_installed
      
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_URL=https://{{ hostvars[groups['k3s_masters'][0]]['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars[groups['k3s_masters'][0]]['node_token']['content'] | b64decode | trim }} sh -
      when: not k3s_agent_installed.stat.exists

- name: Verify cluster
  hosts: k3s_masters[0]
  tasks:
    - name: Get cluster nodes
      shell: kubectl get nodes
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: cluster_nodes
      
    - name: Display cluster status
      debug:
        msg: "{{ cluster_nodes.stdout_lines }}"
